# Generated by Django 2.0.5 on 2018-06-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
